### PR TITLE
[DEV-3930] Create 'TestVendoredBuildConstraints'

### PR DESCRIPTION
**Pull request by HaraldNordgren**
Adding my regression test from here: https://github.com/matryer/moq/issues/48

### CODE REVIEW

**Comment by HaraldNordgren** [comment]
@djui We should also enable Travis builds on PRs. I think that is a Github setting.

Tried to access the settings page using the betalo-team user by couldn't.

**Comment by djui** [comment]
Hm... that's weird. I activated it. Maybe I'm missing some permissions.

**Comment by djui** [comment]
Just checked. The repo was set up in Travis to run, but not in Github to push to it. That's done now.

**Comment by djui** [comment]
But I think you need to close and reopen a PR to make this work. For now Github is just waiting for a build job that never happened.

**Comment by HaraldNordgren** [comment]
Ok, let's try that.

**Comment by djui** [comment]
You need to create a different PR.

**Comment by HaraldNordgren** [comment]
Created another PR (https://github.com/betalo-sweden/moq/pull/3), but I think the real problem sits here:

screencapture-travis-ci-org-betalo-sweden-moq-requests-1518514691881

**Comment by HaraldNordgren** [comment]
Travis won't let me run build jobs because I'm flagged as a "known offender" 🙈

I contacted them via email. Hopefully I can sort this out.

**Pull request merged**
